---

- name: Configure mongodb
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ mongodb_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "mongod.conf.j2"
      dest: "{{ mongodb_conf_file }}"
      user: "root"
      mode: "0644"
    - src: "mongod.key.j2"
      dest: "{{ mongodb_conf_keyfile }}"
      user: "{{ mongodb_user }}"
      mode: "0400"
  notify: mongodb restart

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/mongodb.conf
  when: mongodb_logrotate

- name: Create mongodb user
  user: name={{mongodb_user}} group={{mongodb_user}}

- name: Configure database directory
  file: state=directory path={{ mongodb_conf_dbpath }} owner={{mongodb_user}} group={{mongodb_user}} mode=0755

- name: Configure log directory
  file: state=directory path={{ mongodb_conf_logpath | dirname }} owner={{mongodb_user}} group={{mongodb_user}} mode=0755

- name: Ensure mongodb is started
  service: name={{ mongodb_daemon_name }} state=started enabled=yes

- name: Flush handlers to restart mongodb if necessary
  meta: flush_handlers

- name: Run mongoshell commands
  command: mongo {{ item.key }} --eval "{{ item.value|join(';') }}"
  with_dict: "{{mongodb_shell}}"

