---
- name: configure mongodb group
  group:
    name: "{{ mongodb_daemon_user }}"
    state: present

- name: configure mongodb user
  user:
    name: "{{ mongodb_daemon_user }}"
    group: "{{ mongodb_daemon_group }}"
    state: present

- name: configure mongodb-writable directories
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ mongodb_daemon_user }}"
    group: "{{ mongodb_daemon_group }}"
    mode: "0755"
  with_items:
    - path: "{{ mongodb_conf_dbPath }}"
    - path: "{{ mongodb_conf_logFile | dirname }}"
    - path: "{{ mongodb_conf_pidFile | dirname }}"
  notify: mongodb restart

- name: configure mongodb read-only directories
  file:
    state: directory
    path: "{{ mongodb_conf_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - path: "{{ mongodb_conf_file | dirname }}"
    - path: "{{ mongodb_conf_keyFile | dirname }}"
  notify: mongodb restart

- name: configure mongodb log rotation
  template:
    src: logrotate.conf.j2
    dest: "{{ mongodb_logRotate_file }}"
  when: mongodb_logRotate_enabled

- name: configure mongodb replication key
  template:
    src: "mongod.key.j2"
    dest: "{{ mongodb_conf_keyFile }}"
    owner: root
    group: "{{ mongodb_daemon_group }}"
    mode: "0640"
  when: mongodb_conf_auth
  notify: mongodb restart

- name: configure mongodb daemon
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: mongod.conf.j2
      dest: "{{ mongodb_conf_file }}"
    - src: mongod.service.j2
      dest: "{{ mongodb_daemon_serviceFile }}"
  notify:
    - systemd reload
    - mongodb restart

- meta: flush_handlers
