---
- name: ensure mongo from EPEL is not installed
  yum:
    name:
      - mongodb
      - mongodb-server
    state: absent

- name: ensure no leftovers from previous installations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/mongodb.service
    - /etc/systemd/system/mongodb-server.service
    - /etc/systemd/system/mongodb-org.service
    - /etc/systemd/system/mongodb-org-server.service
  notify: systemd reload

- meta: flush_handlers

- name: install MongoDB RPM GPG key
  rpm_key:
    state: present
    key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_install_major }}.{{ mongodb_install_minor }}.asc"

- name: install MongoDB repo
  yum_repository:
    name: mongodb
    description: "MongoDB Repo"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_install_major }}.{{ mongodb_install_minor }}/$basearch/"
    gpgcheck: true
    state: present

- name: install MongoDB package
  yum: name={{item}} state=present
  with_items:
    - mongodb-org-{{mongodb_install_major}}.{{mongodb_install_minor}}.{{mongodb_install_patch}}
    - mongodb-org-server-{{mongodb_install_major}}.{{mongodb_install_minor}}.{{mongodb_install_patch}}
    - numactl
    - python-pymongo

- name: remove old broken sysV script
  file:
    path: "/etc/rc.d/init.d/mongod"
    state: absent
  notify: reload systemd

- name: configure SELinux file contexts for mongodb
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    reload: true
    state: present
  with_items:
    - target: "{{ mongodb_daemon_bin }}"
      setype: mongod_exec_t
    - target: "{{ mongodb_conf_dbPath | dirname }}(/.*)?"
      setype: mongod_var_lib_t
    - target: "{{ mongodb_conf_logFile | dirname }}(/.*)?"
      setype: mongod_log_t
    - target: "{{ mongodb_conf_pidFile | dirname }}(/.*)?"
      setype: mongod_var_run_t
  notify: mongodb restart

- name: configure SELinux network ports for mongodb
  seport:
    ports: "{{ mongodb_conf_port }}"
    proto: tcp
    setype: mongod_port_t
    reload: true
    state: present
  notify: mongodb restart
