---
- block:
  - name: install MongoDB (RedHat)
    include: install.rpm.yml
    when: ansible_os_family == 'RedHat'
  when: mongodb_install_enabled

- name: configure MongoDB daemon
  include: configure.yml

  #- name: configure MongoDB replication
  #  include: configure.yml

- name: ensure mongodb is started
  service:
    name: mongod
    state: started
    enabled: true

- name: run mongoshell commands
  command: mongo {{ item.key }} --eval "{{ item.value|join(';') }}"
  with_dict: "{{ mongodb_shell_commands }}"
  when: mongodb_shell.run
