---
- name: configure mongodb replication key
  template:
    src: "mongod.key.j2"
    dest: "{{ mongodb_conf_keyFile }}"
    owner: "{{ mongodb_daemon_user }}"
    group: "{{ mongodb_daemon_group }}"
    mode: "0600"
  when: mongodb_conf_auth
  notify: mongodb restart

- name: initiate replica set
  mongodb_replica_set:
    state: initiated
    replset: "{{ mongodb_replSet_name }}"
    login_host: "127.0.0.1"
    login_port: "{{ mongodb_conf_port }}"
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    priority: "501"
    member: "{{ mongodb_replSet_member }}:{{ mongodb_conf_port }}"
  when: mongodb_replSet_isMaster

- name: connect to master
  mongodb_replica_set:
    state: present
    replset: "{{ mongodb_replSet_name }}"
    login_host: "{{ mongodb_replSet_master }}"
    login_port: "{{ mongodb_conf_port }}"
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    member: "{{ mongodb_replSet_member }}:{{ mongodb_conf_port }}"
  when: not mongodb_replSet_isMaster
